name: Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2.1.2

      - name: Build plugin
        run: ./gradlew buildPlugin -PenableWarningAsError=true



